name: Demonstration

on:
  push:
    branches:
      - main
jobs:
  generate_data_job:
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
